import React from 'react'
import Head from 'next/head'

const DocHead = ({title=`Create Next App`, icon=`favicon.ico`, description=`Generated by create next app`, author=`Diego Hartmann`}) => {
  return (
    <Head>
        <title>{title}</title>
        <meta name="description" content={description} />
        <meta name="author" content={author} />
        <link rel="icon" href={`/icons/${icon}`} />
    </Head>
  )
}

export default DocHead