import React from 'react'
import type { NextPage } from 'next'
import styles from './styles.module.css'
import DocHead from '../DocHead'
import PageFooter from '../PageFooter'

interface props{
  //HEAD
  docHeadTitle?: string,
  docHeadIcon?: string,
  docHeadDescription?: string,
  docHeadAuthor?: string,
  //CONTENT
  content?: JSX.Element,
  //FOOTER
  footerHref?:string,
  footerImageUrl?:string,
  footerImageAlt?:string,
  footerImageWidth?:number,
  footerImageHeight?:number,
}

const Page: NextPage <props> = ({
  //HEAD
  docHeadTitle=`Create Next App`,
  docHeadIcon=`favicon.ico`,
  docHeadDescription=`Generated by create next app`,
  docHeadAuthor=`Diego Hartmann`,
  //CONTENT
  content=<div>Page Content</div>,
  //FOOTER
  footerHref=`https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app`,
  footerImageUrl=`/vercel.svg`,
  footerImageAlt=`Vercel Logo`,
  footerImageWidth=72,
  footerImageHeight=16,
}) => {
  return (
    
    <div className={styles.container}>
      
      <DocHead title={docHeadTitle} icon={docHeadIcon} description={docHeadDescription} author={docHeadAuthor}/>

      <main className={styles.main}>
        {content}
      </main>

      <PageFooter 
        href={footerHref}
        imageUrl={footerImageUrl}
        imageAlt={footerImageAlt}
        imageWidth={footerImageWidth}
        imageHeight={footerImageHeight}
      />
      
    </div>
  )
}

export default Page
