import React from 'react'
import type { NextPage } from 'next'
import styles from './styles.module.css'
import DocHead from '../DocHead'
import PageFooter from '../PageFooter'

interface props{
  content: JSX.Element,
  docHeadTitle: string,
  docHeadIcon: string,
  docHeadDescription: string,
  docHeadAuthor: string
}

const Page: NextPage <props> = ({
  content=<div></div>,
  docHeadTitle=`Create Next App`,
  docHeadIcon=`favicon.ico`,
  docHeadDescription=`Generated by create next app`,
  docHeadAuthor=`Diego Hartmann`
}) => {
  return (
    
    <div className={styles.container}>
      
      <DocHead title={docHeadTitle} icon={docHeadIcon} description={docHeadDescription} author={docHeadAuthor}/>

      <main className={styles.main}>
        {content}
      </main>

      <PageFooter/>
      
    </div>
  )
}

export default Page
